layoutdir = "themes/academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://biaslab.github.io"
canonifyurls = true
theme = "academic-group"
title = "BIASlab"
math = true
copyright = "&copy; BIASlab, 2016 "
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "BIASlab"
  email = "mail@example.org"
  address = "3566 Spirit Drive NEW HAVEN Connecticut"
  slogan = "BIASlab"
  slogan_text = "Bayesian Intelligent Autonomous Systems"


  [params.parent_group]
    name = "SPS"
    link = "https://www.tue.nl/en/university/departments/electrical-engineering/research/research-groups/signal-processing-systems-sps/"
  

    [[params.slogan_columns]]
    title = "About"
    text =  "We are an academic research team in the Signal Processing Systems group (EE department) at Eindhoven University of Technology. Our main research interest is in *developing autonomous agents that teach themselves to behave intelligently through interactions with the environment*. Typical application areas include (medical) device personalization, automated vehicle control and robotics."
    link = "#members"
    link_text = "Meet the team"
    weight = 1

  [[params.slogan_columns]]
    title = "Mission"
    text = "Learning through environmental interactions also goes by the name *[Reinforcement Learning](https://en.wikipedia.org/wiki/Reinforcement_learning)*. Our research on reinforcement learning is strongly inspired by developments in  *[Bayesian Inference](https://en.wikipedia.org/wiki/Bayesian_inference)* and *[Computational Neurosciences](https://en.wikipedia.org/wiki/Free_energy_principle)*. Ultimately, we aim to develop a fully Bayesian reinforcement learning framework that is realized by message passing algorithms in highly modular *[Graphical Model](https://en.wikipedia.org/wiki/Graphical_model)* networks."
    link = "/mission"
    link_text = "Read more"
    weight = 2
  [[params.slogan_columns]]
    title = "Approach"
    text = "Our research projects are usually selected by our quest to develop (reinforcement learning) technology to support *in-situ hearing aid personalization*. We 'eat our own dogfood' by immersing ourselves in complex acoustic situations and use our own tools to optimize audio processing algorithms under in-situ conditions. This leads to new problems that drive our next research steps."
    link = "/approach"
    link_text = "Read more"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1

  [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 3

    [[menu.main]]
      name = "Projects"
      url = "#projects"
      weight = 2

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "#posts"
      weight = 4


  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 6
